---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/5 1:43 PM
---

require("eclass")

local CasyncBase = require("async.asyncBase")
local workVar = require("module.workVar")
local sockComm = require("common.sockComm")

local class = class
local Cpingpong = class("pinngpong", CasyncBase)

local running = coroutine.running
local srvSslHandshake = sockComm.srvSslHandshake

function Cpingpong:_init_(beaver, fd, bfd, addr, conf, inst, ctx)
    self._beaver = beaver

    self._bfd = bfd
    self._addr = addr
    self._conf = conf
    self._ctx = ctx
    CasyncBase._init_(self, beaver, fd, 10)
end

function Cpingpong:_setup(fd, tmo)
    local beaver = self._beaver
    local module = self._conf.func
    local ctx = self._ctx
    local ret = 1

    workVar.clientAdd(module, self._bfd, fd, running(), self._addr)

    beaver:co_set_tmo(fd, tmo)
    if ctx then
        ret = srvSslHandshake(beaver, fd, ctx)
    end

    if ret == 1 then
        while true do
            local s = beaver:read(fd)
            if not s then
                break
            end
            local res = beaver:write(fd, s)
            if not res then
                break
            end
        end
    end
    self:stop()
    workVar.clientDel(module, fd)
end

return Cpingpong