---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/5 1:43 PM
---

require("eclass")

local CasyncBase = require("async.asyncBase")
local workVar = require("module.workVar")

local class = class
local Cpingpong = class("pinngpong", CasyncBase)

local running = coroutine.running

function Cpingpong:_init_(beaver, fd, bfd, addr, conf, inst, tmo)
    self._beaver = beaver
    tmo = tmo or 10
    self._bfd = bfd
    self._addr = addr
    self._conf = conf
    CasyncBase._init_(self, beaver, fd, tmo)
end

function Cpingpong:_setup(fd, tmo)
    local beaver = self._beaver
    local module = self._conf.func

    workVar.clientAdd(module, self._bfd, fd, running(), self._addr)
    while true do
        beaver:co_set_tmo(fd, tmo)
        local s = beaver:read(fd)
        if not s then
            break
        end
        beaver:co_set_tmo(fd, tmo)
        local res = beaver:write(fd, s)
        if not res then
            break
        end
    end
    self:stop()
    workVar.clientDel(module, fd)
end

return Cpingpong