log:
  out: "syslog"
worker:
  - number: 1   # worker process
    # clientCoding: "gzip"  - client accept encoding, default is "deflate, gzip", if set "", no accept-encoding
    funcs:
    - func: "pingpong"
      mode: "TCP"
      bind: "0.0.0.0"
      port: 3382
    - func: "dnsReq"
      mode: "TCP"
      bind: "0.0.0.0"
      port: 3383
    - func: "upstream"
      mode: "TCP"
      bind: "0.0.0.0"
      port: 3384
      upIP: "172.16.0.131"
      upPort: 3385
    - func: "httpServer"
      mode: "TCP"
      bind: "0.0.0.0"
      port: 3385
      gzip: true
      entry: test  # entry path
    - func: "tcpServer"
      mode: "TCP"
      uniSock: "/tmp/uds.sock"
      entry: udsServer
  # - number: 1
  #   entries:
  #   - entry: timeWork
