---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/12/31 8:06 AM
---

local unistd = require("posix.unistd")
local cffi = require("beavercffi")
local CcoBeaver = require("coBeaver")
local CasyncPipeRead = require("async.asyncPipeRead")
local CasyncPipeWrite = require("async.asyncPipeWrite")
local conf

local print = print

function init(fIn, fOut, name, config)
    conf = {
        fIn = fIn,
        fOut = fOut,
        name = name,
        config = config
    }
    return 0
end

function work()
    print(conf.name)
    local module = require("module." .. conf.name)
    local m = module.new(conf)
    m:proc()
    return 0
end