---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/12/31 8:06 AM
---

local unistd = require("posix.unistd")
local cffi = require("beavercffi")
local CcoBeaver = require("coBeaver")
local CasyncPipeRead = require("async.asyncPipeRead")
local CasyncPipeWrite = require("async.asyncPipeWrite")
local conf

function init(f_in, f_out, name, config)
    conf = {
        f_in = f_in,
        f_out = f_out,
        name = name,
        config = config
    }
    return 0
end

function work()
    print(conf.name)
    local module = require("module." .. conf.name)
    local m = module.new(conf)
    m:proc()
    return 0
end