---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/18 4:44 PM
---

require("eclass")

local system = require("common.system")
local pystring = require("pystring")
local cjson = require("cjson.safe")
local ChttpReq = require("http.httpReq")
local Credis = require("client.redis")

local Ctest = class("test")

local counter = 0

local function index(tReq)
    counter = counter + 1
    return {body = string.format("beaver %d say hello.", counter)}
end

local proxy = {
    ip = "172.16.0.119",
    port = 3128
}

local function instance(tReq)
    local req = ChttpReq.new(tReq, "100.100.100.200", 80)
    local tRes = req:get("/latest/meta-data/instance-id")
    if tRes then
        return {body = tRes.body}
    end
end

local function bing(tReq)
    local req = ChttpReq.new(tReq, "cn.bing.com", nil, nil, proxy)
    local tRes = req:get("HTTP://cn.bing.com/")
    if tRes then
        return {body = tRes.body}
    end
end

local function baidu(tReq)
    local req = ChttpReq.new(tReq, "www.baidu.com", nil, nil, proxy)
    local tRes = req:get("HTTP://www.baidu.com/")
    if tRes then
        return {body = tRes.body}
    end
end

local function rset(tReq)
    local r = Credis.new(tReq, "172.16.0.136", 3341)
    local s = tReq.body
    local k, v = unpack(pystring.split(s, ":", 1))
    local res = r:set(k, v)
    if res then
        return {body = res}
    end
end

local function rget(tReq)
    local r = Credis.new(tReq, "172.16.0.136", 3341)
    local s = tReq.body
    local res = r:get(s)
    if res then
        return {body = res}
    end
end

local function rcmds(tReq)
    local r = Credis.new(tReq, "172.16.0.136", 3341)
    local pipe = r:pipeline()
    
    local s = tReq.body
    local cmds = pystring.split(s, "\n")
    for _, cmdLine in ipairs(cmds) do
        local cmd, argStr = unpack(pystring.split(cmdLine, " ", 1))
        local args = pystring.split(argStr, ":")
        pipe[cmd](pipe, unpack(args))
    end
    local res = pipe:send()
    if res then
        return {body = cjson.encode(res)}
    end
end

function Ctest:_init_(inst, conf)
    inst:get("/", index)
    inst:get("/instance", instance)
    inst:get("/bing", bing)
    inst:get("/baidu", baidu)
    inst:post("/rset", rset)
    inst:post("/rget", rget)
    inst:post("/rcmds", rcmds)
end

return Ctest
