---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/3 4:30 AM
---

require("eclass")

local CasyncBase = require("async.asyncBase")

local CasyncReadSize = class("asyncReadSize", CasyncBase)

function CasyncReadSize:_init_(beaver, fd, size, tmo)
    self._size = size
    self._toWake = coroutine.running()
    tmo = tmo or 10
    CasyncBase._init_(self, beaver, fd, tmo)
end

function CasyncReadSize:_setup(fd, tmo)
    local stream = self._beaver:readBySize(fd)
    coroutine.resume(self._toWake, stream)
end

return CasyncReadSize