---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/3 4:34 AM
---

require("eclass")

local CasyncBase = require("async.asyncBase")

local CasyncWrite = class("asyncWrite", CasyncBase)

function CasyncWrite:_init_(beaver, fd, stream, tmo)
    self._stream = stream
    self._toWake = coroutine.running()
    CasyncBase._init_(self, beaver, fd, tmo)
end

function CasyncWrite:_setup(fd, tmo)
    local ret = self._beaver:write(fd, self._stream)
    coroutine.resume(self._toWake, ret)
end

return CasyncWrite