---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/3 4:37 AM
---

require("eclass")

local CasyncBase = require("async.asyncBase")

local CasyncPipeWrite = class("asyncPipeWrite", CasyncBase)

function CasyncPipeWrite:_init_(beaver, fd, stream, tmo)
    self._stream = stream
    self._toWake = coroutine.running()
    tmo = tmo or 10
    CasyncBase._init_(self, beaver, fd, tmo)
end

function CasyncPipeWrite:_setup(fd, tmo)
    local stream = self._beaver:pipeWrite(fd, self._stream)
    coroutine.resume(self._toWake, stream)
end

return CasyncPipeWrite