---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/3 4:04 AM
---

require("eclass")

local CasyncBase = require("async.asyncBase")

local CasyncRead = class("asyncRead", CasyncBase)

function CasyncRead:_init_(beaver, fd, size, tmo)
    self._size = size
    self._toWake = coroutine.running()
    CasyncBase._init_(self, beaver, fd, tmo)
end

function CasyncRead:_setup(fd, tmo)
    local stream = self._beaver:read(fd, self._size)
    coroutine.resume(self._toWake, stream)
end

return CasyncRead
