---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/1 11:51 PM
---

require("eclass")

local unistd = require("posix.unistd")
local CasyncBase = require("async.asyncBase")

local CasyncIO = class("asyncIO", CasyncBase)

function CasyncIO:_init_(beaver, fd)
    CasyncBase._init_(self, beaver, fd)
end

function CasyncIO:_setup(fd, tmo)

end

return CasyncIO