---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/4 10:58 PM
---

require("eclass")
local CcoBeaver = require("coBeaver")
local CasyncPipeRead = require("async.asyncPipeRead")
local CasyncPipeWrite = require("async.asyncPipeWrite")

local lyaml = require("lyaml")

local Cmaster = class("master")

function Cmaster:_init_(config)
    self._config = config
end

local function work(b, conf)
    local r = CasyncPipeRead.new(b, conf.f_in, -1)
    local w = CasyncPipeWrite.new(b, conf.f_out, 10)

    while true do
        local s = r:read()
        print(s)
        w:write(s)
    end
end

function Cmaster:proc()
    local b = CcoBeaver.new()
    local co = coroutine.create(work)
    local res, msg = coroutine.resume(co, b, self._conf)
    assert(res, msg)
    b:poll()
    return 0
end

return

